// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AlarmSystem.Models;

public partial class AlarmGroup
{
    public string GroupId { get; set; }

    public string GroupName { get; set; }

    public bool Enable { get; set; }

    public DateTime CreateDate { get; set; }
}