// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AlarmSystem.Models;

public partial class AlarmSettings
{
    public int Id { get; set; }

    public string Stid { get; set; }

    public string ParameterColumn { get; set; }

    public string ParameterShow { get; set; }

    public int Threshold { get; set; }

    public TimeOnly StartTime { get; set; }

    public TimeOnly EndTime { get; set; }

    public DateTime? NextCheckTime { get; set; }

    public virtual AlarmItem St { get; set; }
}