// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AlarmSystem.Models;

public partial class AlarmItems
{
    public string Stid { get; set; }

    public string GroupId { get; set; }

    public string Location { get; set; }

    public string ParameterColumn { get; set; }

    public int Threshold { get; set; }

    public string ParameterShow { get; set; }

    public int AlarmDelay { get; set; }

    public TimeOnly AlarmTimeStart { get; set; }

    public TimeOnly AlarmTimeEnd { get; set; }

    public DateTime? AlarmCheckTime { get; set; }
}