// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AlarmSystem.Models;

public partial class Sysadmin
{
    public string UserId { get; set; }

    public string Account { get; set; }

    public string Password { get; set; }

    public DateTime CreateDate { get; set; }
}