// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace LineSystem.Models;

public partial class LineAlarmContext : DbContext
{
    public LineAlarmContext(DbContextOptions<LineAlarmContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AlarmItems> AlarmItems { get; set; }

    public virtual DbSet<LineGroups> LineGroups { get; set; }

    public virtual DbSet<Sysadmin> Sysadmin { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.HasDefaultSchema("jsene");

        modelBuilder.Entity<AlarmItems>(entity =>
        {
            entity.HasKey(e => new { e.Stid, e.ParameterColumn, e.Threshold }).HasName("PK_StationInfo_1");

            entity.ToTable("AlarmItems", "dbo");

            entity.Property(e => e.Stid)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.ParameterColumn)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.GroupId)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Location)
                .IsRequired()
                .HasMaxLength(30);
            entity.Property(e => e.ParameterShow)
                .IsRequired()
                .HasMaxLength(30);
            entity.Property(e => e.Threshold)
                .IsRequired();
            entity.Property(e => e.AlarmTimeEnd)
                .HasPrecision(0)
                .HasDefaultValue(new TimeOnly(23, 59, 59));
            entity.Property(e => e.AlarmTimeStart).HasPrecision(0);
        });

        modelBuilder.Entity<LineGroups>(entity =>
        {
            entity.HasKey(e => e.GroupId);

            entity.ToTable("LineGroups", "dbo");

            entity.Property(e => e.GroupId)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.AlarmDelay).HasDefaultValue(60);
            entity.Property(e => e.Enable).HasDefaultValue(true);
            entity.Property(e => e.GroupName).HasMaxLength(50);
        });

        modelBuilder.Entity<Sysadmin>(entity =>
        {
            entity.HasKey(e => e.UserId);

            entity.ToTable("Sysadmin", "dbo");

            entity.Property(e => e.UserId)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Account)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}