// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LineSystem.Models;

public partial class LineGroups
{
    public string GroupId { get; set; }

    public string GroupName { get; set; }

    public int AlarmDelay { get; set; }

    public bool Enable { get; set; }
}